#!/usr/bin/perl

use strict;
use warnings;
use DBI;

$|=1;


sub randompass()
{
	my @alphanumeric = ('a'..'z', 'A'..'Z', 0..9,'!','_','-');
	my @numeric = (0..9);
	my $randpassword = '';

	while ( length($randpassword) < 8 ) {
              $randpassword = $randpassword . join '', map $alphanumeric[rand @alphanumeric], 0..(rand @numeric);
	}
	$randpassword .= '#';
	return $randpassword;
}

# We will just rebuild experiment name and 
# start SSH tunnel and novnc proxy
my $SSH = "ssh -o StrictHostKeyChecking=no";
    
# Take paper ID, type of VM to stop and user ID
# and set up SSH tunnel and novnc proxy

my $usage="$0 paper-ID vm-type user-ID node-ID\n";
my %opt = ();


if ($#ARGV < 3)
{
    print $usage;
    print "DONE";
    exit 1;
}

# Read info from conf/options.php
# to get orgName, dbUser, etc.
my $fh = new IO::File("conf/options.php");
while (<$fh>)
{
    if ($_ =~ /\$Opt/ && $_ =~ /\=/)
    {
	my @arr = split /[\[\]\"\=\s+\;]/, $_;	
	if ($#arr > 3)
	{
	    my $intake = 0;
	    for my $a (@arr)
	    {
		if ($a !~ /[\[\]\"\=\s+]/ && $a =~ /[a-zA-Z0-9]/)
		{
		    if ($a =~ /^\$Opt/)
		    {
			$intake = 1;
			next;
		    }
		    if ($intake =~ /^[0-9]$/ && $intake == 1)
		    {
			$opt{$a} = 0;
			$intake = $a;
		    }
		    else
		    {
			$opt{$intake} = $a;
			last;
		    }
		}
	    }
	}
    }
}
close($fh);


my $dsn = "DBI:mysql:database=$opt{'dbName'}";
my $dbh = DBI->connect($dsn, $opt{'dbUser'}, $opt{'dbPassword'});
my $sth;
my $paperID = $ARGV[0];
my $vmtype = $ARGV[1];
my $userID = $ARGV[2];
my $nodeID = $ARGV[3];
# Set server
my $cmd="mrg config set server grpc.mod.deterlab.net";
system($cmd);
my $proj = $opt{'clusterOrg'} . "p" . $paperID;
my $vmid = $vmtype . "." . $proj;
# Org owner will always have an account on VM even when they are not a reviewer or author
$sth = $dbh->prepare(
	'SELECT username from ClusterUsers where contactID=1')
	or die "prepare statement failed: $dbh->errstr()";
$sth->execute() or die "execution failed: $dbh->errstr()";
my $ref = $sth->fetchrow_hashref();
my $ownerusername = $ref->{'username'};
my $hasaccess = 0;
# Check if org owner is on the list for access to this VM
$sth = $dbh->prepare(
	'SELECT * FROM VMaccess vm left join ClusterUsers cu on vm.contactID=cu.contactID where vmid = ? and vm.contactID = 1')
        or die "prepare statement failed: $dbh->errstr()";
$sth->execute($vmid) or die "execution failed: $dbh->errstr()";
if ($sth->rows > 0)
{
    $hasaccess=1;
}
# Calculate which terminal ID should user have
$sth = $dbh->prepare(
	'SELECT username, vm.contactID FROM VMaccess vm left join ClusterUsers cu on vm.contactID=cu.contactID where vmid = ? order by contactID asc ')
	or die "prepare statement failed: $dbh->errstr()";
$sth->execute($vmid) or die "execution failed: $dbh->errstr()";
my $i=0;
my $found=0;
my $username = "";
while (my $ref = $sth->fetchrow_hashref()) {
    my $ID = $ref->{'contactID'};
    $username = $ref->{'username'};
    if ($ID == $userID)
    {
	$found = 1;
	last;
    }
    $i++;
}
if ($found == 0)
{
    print "This user has no access to the given VM\n";
    print "DONE";
    exit 1;
}
my $termID = $i;
# Now check if org owner's presence on that VM intereferes with termID calculation
if (!$hasaccess && $ownerusername lt $username)
{
    $termID++;
}
# Find port numbers that would go with this instance
$sth = $dbh->prepare(
        'SELECT portId FROM Ports where vmid = ? and contactId = ? and node = ?')
    or die "prepare statement failed: $dbh->errstr()";
$sth->bind_param(1, "$vmid");
$sth->bind_param(2, $userID);
$sth->bind_param(3, "$nodeID");
$sth->execute() or die "execution failed: $dbh->errstr()";
my $offset = 0;
if ($sth->rows > 0)
{
    my $ref = $sth->fetchrow_hashref();
    $offset = $ref->{'portId'};
}
else
{
    $sth = $dbh->prepare(
        'INSERT INTO Ports(vmid, contactId, node) values (?, ?, ?)')
	or die "prepare statement failed: $dbh->errstr()";
    $sth->bind_param(1, "$vmid");
    $sth->bind_param(2, $userID);
    $sth->bind_param(3, "$nodeID");
    $sth->execute() or die "execution failed: $dbh->errstr()";
    $sth = $dbh->prepare(
        'SELECT portId FROM Ports where vmid = ? and contactId = ? and node = ?')
	or die "prepare statement failed: $dbh->errstr()";
    $sth->bind_param(1, "$vmid");
    $sth->bind_param(2, $userID);
    $sth->bind_param(3, "$nodeID");
    $sth->execute() or die "execution failed: $dbh->errstr()";
    my $ref = $sth->fetchrow_hashref();
    $offset = $ref->{'portId'};
}    
print "Offset $offset\n";
my $vncport = $termID + 5900;
my $port = 10000 + $offset;
my $proxyport = 6080 + $offset;
print "Port $port proxyport $proxyport term ID $termID offset $offset\n";
my $path=$opt{'webpath'};
$ENV{HOME}=$path;
my $config = "$path/config";
my $admin=$opt{'clusterUser'};
my $logincmd =  "mrg login " . $opt{'clusterUser'} . " -p \"" . $opt{'clusterPass'} . "\"";
# Log in as conf admin and as www-data user
$cmd = $logincmd;
my $result=system($cmd);
# Log in as conf admin and as merge user
$cmd = "sudo -H -u merge " . $logincmd;
my $result=system($cmd);
open(my $oh, '>', $config); # or die $!;
print $oh "
Host *
     IdentityFile $path/.ssh/merge_key
     ServerAliveInterval 30
     User $admin
     StrictHostKeyChecking no
     ProxyCommand ssh -o StrictHostKeyChecking=no -p 2022 -i $path/.ssh/merge_key -W %h:%p $admin\@jump.mod.deterlab.net";
close($oh);
# Create similar config for merge user
my $mconfig = "/tmp/config";
open($oh, '>', $mconfig); # or die $!;
print $oh "                                                                                                                                                                                                                           
Host *	
    IdentityFile /home/merge/.ssh/merge_key
    ServerAliveInterval 30
    User $admin
    StrictHostKeyChecking no
    UserKnownHostsFile=/dev/null
    ProxyCommand ssh -o StrictHostKeyChecking=no -p 2022 -i /home/merge/.ssh/merge_key -W %h:%p $admin\@jump.mod.deterlab.net";
close($oh);
my $output = `ps axuw | grep ssh | grep "localhost:$port " | wc | awk '{print \$1}'`;
if ($output <= 1)
{
    # Delete known_hosts on XDC just in case
    my $xdccmd = "rm /home/" . $opt{'clusterUser'} . "/.ssh/known_hosts 2>&1";
    $cmd = "sudo -u merge ssh -F $mconfig xdc-$proj \"$xdccmd\"";
    $result=system($cmd);
    print "Creating new SSH tunnel";
    $cmd = "sudo -u merge ssh -F $mconfig -L " . $port . ":localhost:" . $port . " xdc-$proj -t ssh -L " . $port . ":localhost:" . $vncport . " -N node 2>&1 </dev/null &";
    $result=system($cmd);
    if ($result != 0)
    {
	print "SSH tunnel creation failed\n";
	print "DONE";
	exit 1;
    }
}
$output = `ps axuw | grep novnc_proxy | grep "localhost:$port " | wc | awk '{print \$1}'`;
if ($output <= 1)
{
    print "Starting novnc proxy";
    $cmd = "/var/noVNC/utils/novnc_proxy --vnc localhost:" . $port . " --listen $proxyport 2>&1 &";
    my $result=system($cmd);
    if ($result != 0)
    {
	print "novnc_proxy failed\n";
	print "DONE";
	exit 1;
    }
}
print "DONE";
