#!/usr/bin/perl

use strict;
use warnings;
use DBI;

$|=1;


# We will just rebuild experiment name and 
# extend lifetime
my $SSH = "ssh -o StrictHostKeyChecking=no";
    
# Take paper ID, type of VM to stop
# and build a name
# like extend 2 small 

my $usage="$0 paper-ID vm-type\n";
my %opt = ();


if ($#ARGV < 1)
{
    print $usage;
    print "DONE";
    exit 1;
}

# Read info from conf/options.php
# to get orgName, dbUser, etc.
my $fh = new IO::File("conf/options.php");
while (<$fh>)
{
    if ($_ =~ /\$Opt/ && $_ =~ /\=/)
    {
	my @arr = split /[\[\]\"\=\s+\;]/, $_;	
	if ($#arr > 3)
	{
	    my $intake = 0;
	    for my $a (@arr)
	    {
		if ($a !~ /[\[\]\"\=\s+]/ && $a =~ /[a-zA-Z0-9]/)
		{
		    if ($a =~ /^\$Opt/)
		    {
			$intake = 1;
			next;
		    }
		    if ($intake =~ /^[0-9]$/ && $intake == 1)
		    {
			$opt{$a} = 0;
			$intake = $a;
		    }
		    else
		    {
			$opt{$intake} = $a;
			last;
		    }
		}
	    }
	}
    }
}
close($fh);


my $dsn = "DBI:mysql:database=$opt{'dbName'}";
my $dbh = DBI->connect($dsn, $opt{'dbUser'}, $opt{'dbPassword'});
my $sth;
my %tocreate=();
my $paperID = $ARGV[0];
my $vmtype = $ARGV[1];
# Set server
my $path=$opt{'webpath'} . "/secret";
$ENV{HOME}=$path;
my $cmd="mrg config set server grpc.mod.deterlab.net";
system($cmd);
# Call mrg update
my $logincmd =  "mrg login " . $opt{'clusterUser'} . " -p \"" . $opt{'clusterPass'} . "\"";
my $proj = $opt{'clusterOrg'} . "p" . $paperID;
my $vmid = $vmtype . "." . $proj;
# Log in as conf admin and as www-data user
$cmd = $logincmd;
my $result=system($cmd);
$cmd = "mrg update realization expiration real.$vmtype.$proj 1w";
my $result = system($cmd);
if ($result != 0)
{
    print "VM lifetime could not be extended\n";
    print "DONE";
    exit 1;
}
my $new_time=time() + 7*24*3600;
$sth = $dbh->prepare(
    'UPDATE VMs set end_time=? WHERE vmid=?')
    or die "prepare statement failed: $dbh->errstr()";
$sth->bind_param(1, $new_time);
$sth->bind_param(2, $vmid);
$sth->execute or die "execution failed: $dbh->errstr()";
$sth->finish;
print "DONE\n";
exit 0;
